[settings]
experimental = true
legacy_version_file = true
all_compile = false

[tools]
agy = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"

lua-language-server = "latest"
stylua = "latest"
shfmt = "latest"
shellcheck = "latest"
marksman = "latest"

node = "lts"
"npm:bash-language-server" = "latest"
