import = [
    "/home/dwaris/.dotfiles/alacritty/.config/alacritty/theme/catppuccin/catppuccin-mocha.toml",
]
live_config_reload = true

[font]
size = 12

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "bash"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"
