import = ["~/.config/alacritty/theme/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true

[font]
size = 12.0

[font.normal]
family = "Source Code Pro"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/run/current-system/sw/bin/bash"

[window]
opacity = 0.9
dynamic_title = true
decorations = "Full"
#startup_mode = "Maximized" still buggy
