import = ["~/.config/alacritty/theme/catppucin/catppuccin-mocha.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true

[font]
size = 12.0

[font.normal]
family = "Source Code Pro"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
dynamic_title = true
decorations = "Full"
#startup_mode = "Maximized" currently broken lol
