return {
    -- {
    --     'github/copilot.vim',
    --     config = function()
    --         vim.g.copilot_no_tab_map = true
    --
    --         vim.keymap.set('i', '<M-l>', 'copilot#Accept("\\<CR>")', {
    --             expr = true,
    --             replace_keycodes = false,
    --             desc = 'Copilot accept',
    --         })
    --         vim.keymap.set('i', '<M-]>', '<Plug>(copilot-next)', {
    --             desc = 'Copilot next',
    --         })
    --         vim.keymap.set('i', '<M-[>', '<Plug>(copilot-previous)', {
    --             desc = 'Copilot previous',
    --         })
    --         vim.keymap.set('i', '<C-]>', '<Plug>(copilot-dismiss)', {
    --             desc = 'Copilot dismiss',
    --         })
    --     end,
    -- },
}
