return {
    {
        'nvim-treesitter/nvim-treesitter',
        opts = {
            ensure_installed = {
                'bash',
                'c',
                'glsl',
                'go',
                'html',
                'javascript',
                'java',
                'kotlin',
                'latex',
                'json',
                'jsonc',
                'lua',
                'markdown',
                'markdown_inline',
                'python',
                'query',
                'regex',
                'rust',
                'toml',
                'tsx',
                'typescript',
                'vim',
                'yaml',
            },
        },
    },
}
