profile=gpu-hq
vo=gpu-next
gpu-api=vulkan
target-colorspace-hint=no

# Deband filter. Always turn on for anime.
#deband=yes

# Deband parameters configuration.
deband-iterations=4 # Range 1-16. Higher = better quality but more GPU usage. >5 is redundant.
deband-threshold=35 # Range 0-4096. Deband strength.
deband-range=16 # Range 1-64. Range of deband. Too high may destroy details.
deband-grain=4 # Range 0-4096. Inject grain to cover up bad banding, higher value needed for poor sources.

#dither-depth=auto

video-sync=display-resample
interpolation
tscale=oversample
scale-blur=0.981251
scale=ewa_lanczos
#cscale=ewa_lanczos
#dscale=mitchell

###### Luma up (uncomment FSRCNNX or SSimSuperRes, not both)
glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1_LineArt.glsl" # mathematically best, most expensive
#glsl-shader="~~/shaders/SSimSuperRes.glsl"               # really good, a little cheaper for the GPU

###### Luma down
glsl-shader="~~/shaders/SSimDownscaler.glsl"
dscale=mitchell
linear-downscaling=no
correct-downscaling=yes

###### Chroma up + down
glsl-shader="~~/shaders/KrigBilateral.glsl"
cscale=mitchell

###### Antiring
scale-antiring=0.7
dscale-antiring=0.7
cscale-antiring=0.7

#audio-channels=stereo
#af=acompressor
volume=100
volume-max=200

alang = 'jpn,jp,eng,en'
slang = 'eng,en,enUS'

demuxer-mkv-subtitle-preroll=yes
sub-auto=fuzzy

save-position-on-quit
