background = 0xFF11111B
base = 0xFF1E1E2E
alternate_base = 0xFF181825
text = 0xFFCDD6F4
bright_text = 0xFFF5E0DC
accent = 0xFFCBA6F7

rounding_large = 8
rounding_small = 4

font_family = IBM Plex Sans
