general {
    lock_cmd = pidof hyprlock || hyprlock                                       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                    # lock before suspend.
}

listener {
    timeout = 150                                                               # 2.5min.
    on-timeout = brightnessctl -c backlight -s set 10 || true                   # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -c backlight -r || true                           # monitor backlight restore.
}

listener {
    timeout = 150                                                                                                       # 2.5min.
    on-timeout = brightnessctl -l | grep -q 'kbd_backlight' && brightnessctl -sd '*::kbd_backlight' set 0 || true       # turn off kbd backlight
    on-resume = brightnessctl -l | grep -q 'kbd_backlight' && brightnessctl -rd '*::kbd_backlight' || true              # restore kbd backlight
}

listener {
    timeout = 300                                                               # 5min
    on-timeout = loginctl lock-session                                          # lock screen
}

listener {
    timeout = 330                                                               # 5.5min (30s after lock)
    on-timeout = brightnessctl -c backlight -s set 0 || true                   # turn laptop screen completely black
    on-resume = brightnessctl -c backlight -r || true                          # restore brightness
}

listener {
    timeout = 1800                                                              # 30min
    on-timeout = loginctl suspend                                               # suspend pc
}
