general {
    lock_cmd = pidof hyprlock || hyprlock                                   # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150                                                # 2.5min.
    on-timeout = brightnessctl -c backlight -s set 10 || true   # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -c backlight -r || true           # monitor backlight restore.
}

listener {
    timeout = 300                                               # 5min
    on-timeout = brightnessctl -l | grep -q 'kbd_backlight' && brightnessctl -sd '*::kbd_backlight' set 0 || true
    on-resume = brightnessctl -l | grep -q 'kbd_backlight' && brightnessctl -rd '*::kbd_backlight' || true
}

listener {
    timeout = 300                                                                           # 5min
    on-timeout = loginctl lock-session && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' # lock with 30s grace and turn off screen
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && (brightnessctl -c backlight -r || true)   # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
