[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vicmd_symbol = '[V](bold green)'

[username]
style_user = "bold purple"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
format = "[@](bold)[$hostname](bold yellow) "

[cmd_duration]
min_time = 5_000
format = "[$duration](bold yellow) "

